<div class="content-wrapper">
    <div class="content-sidebar transparent">
        <div>
            <?php
            if($this->request_detail['request_status_id']==1)
            {
            ?>
                <button type="submit" class="btn-grey" <?php if($this->ob_LoginAuth->chk_menu_permission('Request_Approve')) { ?> onclick="window.location='/Request/manage/idd/<?php echo $this->idd;?>/status/2'" <?php } else { print 'disabled'; } ?>>Approve</button>
                <button type="submit" class="btn-accent" <?php if($this->ob_LoginAuth->chk_menu_permission('Request_Reject')) { ?> onclick="window.location='/Request/manage/idd/<?php echo $this->idd;?>/status/3'" <?php } else { print "disabled"; }?> >Reject</button>
            <?php
            }else if($this->request_detail['request_status_id']==2)
            {
            ?>
                <button type="submit" class="btn-green">Approved</button>

            <?php
            }else{
            ?>
            <button type="submit" class="btn-red">Rejected</button>
            <?php
            }

            ?>

        </div>
        <table class="table-simple">
            <tr class="condense">
                <td><?php echo $this->request_detail['company_name'];?></td>
                <td class="pull-left"></td>
            </tr>
            <tr class="condense">
                <td><?php echo $this->request_detail['request_status_name'];?></td>
                <td class="pull-left"></td>
            </tr>

        </table>
    </div>
    <h2 class="heading"><?php echo $this->request_detail['req_gen_id'];?></h2>
    <h3 class="sub-title sm-font bold"><?php echo $this->request_detail['customer_name'];?></h3>
    <div class="content-main full">
        <form class="default-form">
            <table class="table-simple athird bordered">
                <tbody>
                <tr class="border-bottom">
                    <td class="bold">Assigned Vehicle:</td>
                    <td class="align-left"><?php echo $this->request_detail['assigned_vehicle_name'] ? $this->request_detail['assigned_vehicle_name'] : 'N/A';?></td>

                    <td class="bold">Payment Method:</td>
                    <td class="align-left"><?php echo $this->request_detail['payment_method_name'] ? $this->request_detail['payment_method_name'] : 'N/A';?></td>
                </tr>
                <tr class="border-bottom">
                    <td class="bold">Package:</td>
                    <td class="align-left"><?php echo $this->request_detail['package_name'] ? $this->request_detail['package_name'] : 'N/A';?></td>


                    <td class="bold">Estimated Price (Php):</td>
                    <td class="align-left"><?php echo $this->request_detail['estimated_price'] ? number_format($this->request_detail['estimated_price'] ,2) : 'N/A';?></td>
                </tr>
                <tr class="border-bottom">
                    <td class="bold">Rate:</td>
                    <td class="align-left"><?php echo $this->request_detail['request_rate_name'] ? $this->request_detail['request_rate_name'] : 'N/A';?></td>


                    <td class="bold">Reservation Source:</td>
                    <td class="align-left">N/A</td>
                </tr>
                <tr class="border-bottom">
                    <td class="bold">Rent From:</td>
                    <td class="align-left"><?php echo $this->request_detail['rent_from'] ? $this->request_detail['rent_from'] : 'N/A';?></td>

                    <td class="bold">Notes:</td>
                    <td class="align-left"><?php echo $this->request_detail['note'] ? $this->request_detail['note'] : 'N/A';?></td>
                </tr>
                <tr class="border-bottom">
                    <td class="bold">Rent To:</td>
                    <td class="align-left"><?php echo $this->request_detail['rent_to'] ? $this->request_detail['rent_to'] : 'N/A';?></td>

                    <td class="bold">Created By:</td>
                    <td class="align-left"><?php echo $this->request_detail['requested_by_name'] ? $this->request_detail['requested_by_name'] : 'N/A';?></td>
                </tr>
                <tr class="border-bottom">
                    <td class="bold">Delivery Address:</td>
                    <td class="align-left"><?php echo $this->request_detail['delivery_address'] ? $this->request_detail['delivery_address'] : 'N/A';?></td>

                    <td class="bold">Approved By:</td>
                    <td class="align-left"><?php echo $this->request_detail['requested_by_name'] ? $this->request_detail['requested_by_name'] : 'N/A';?></td>
                </tr>
                <tr class="border-bottom">
                    <td class="bold">Assigned Driver 1:</td>
                    <td class="align-left"><?php echo $this->request_detail['assigned_driver_1_id_name'] ? $this->request_detail['assigned_driver_1_id_name'] : 'N/A';?></td>

                    <td class="bold">Updated On:</td>
                    <td class="align-left"><?php echo $this->request_detail['mod_date'] ? $this->request_detail['mod_date'] : 'N/A';?></td>
                </tr>
                <tr class="border-bottom">
                    <td class="bold">Pickup Address:</td>
                    <td class="align-left"><?php echo $this->request_detail['pickup_address'] ? $this->request_detail['pickup_address'] : 'N/A';?></td>

                    <td class="bold"></td>
                    <td class="align-left"></td>
                </tr>
                <tr class="border-bottom">
                    <td class="bold">Assigned Driver 2:</td>
                    <td class="align-left"><?php echo $this->request_detail['assigned_driver_2_id_name'] ? $this->request_detail['assigned_driver_2_id_name'] : 'N/A';?></td>

                    <td class="bold"></td>
                    <td class="align-left"></td>
                </tr>





                </tbody>
            </table>
            <table class="table-simple athird bordered">
                <tr class="border-bottom">
                    <?php
                    if(count($this->request_images) > 0)
                    {
                        $sl=1;
                        foreach($this->request_images as $k=>$v)
                        {
                            if(count($this->request_images)==1)
                            {
                                $width = '25%';
                            }elseif(count($this->request_images)==2)
                            {
                                $width = '50%';
                            }elseif(count($this->request_images)==3)
                            {
                                $width = '75%';
                            }else{
                                $width = '100%';
                            }
                            ?>
                            <td><img src="/public/uploads/request/<?php echo $v['image_name'];?>" width="<?php echo $width;?>"></td>

                        <?php
                        }
                    }
                    ?>


                </tr>
            </table>
            <div class="group">
                <button type="button" onclick="cancel('<?php echo $this->cancel_link?>');" class="btn-grey">Go back to list</button></div>
        </form>



    </div>






</div>