<?php
$user_details=$this->user_rows;
?>
<script src="<?php echo $this->site_asset ;?>js/defined_list_fucntions.js"></script>
<script type="application/javascript">
    function check_sub()
    {
        //alert('all done');return false;
    }
    function del_row(idd,nnme)
    {
        if(confirm('Are You Sure to Delete user ('+nnme+')'))
        {
            $("#del_id").val(idd);
            $("#search_form").submit();
        }
    }
    function active_row(idd,nnme,ttype)
    {
        var sstr=(ttype*1)?"Un-lock":"Lock";
        if(confirm('Are You Sure to '+sstr+' user ('+nnme+')'))
        {
            $("#act_id").val(idd);
            $("#act_type").val(ttype);
            $("#search_form").submit();
        }
    }

    function del_con_checkit()
    {
        var valid = '';
        var val = [];
        $(':checkbox:checked').each(function(i){
            val[i] = $(this).val();
        });

        if(confirm("Are you sure you want to delete?"))
        {
            $.ajax({
                type: 'POST',
                url: "/request/mutideleterequest/",
                data: { del_ids: val }
            }).done(function(data) {

                    window.location = '/Request/listwfa';

                });

        }else{
            alert("Canceled");
            window.location = '/Request/listwfa';
        }
    }




</script>
<div class="content-wrapper">

    <div class="">
        <h2 class="heading bold">List Request For approval</h2>
    </div>


    <div class="content-main full">
        <div class="team-title">
            <div class="block">
                <?php if($this->ob_LoginAuth->chk_menu_permission('Add_Request_WFA')){?>
                    <button class="md-font btn-green" onclick="window.location='/Request/manage'"><i class="fa fa-bell"></i> Add Request</button>
                <?php } ?>
                <?php if($this->ob_LoginAuth->chk_menu_permission('Delete_Request_WFA')){ ?>
                    <button class="md-font btn-red" id="delbtn" onclick="del_con_checkit();"><i class="fa fa-trash"></i> Delete</button>
                <?php } ?>
                <?php if($this->ob_LoginAuth->chk_menu_permission('Import_Request_WFA')){ ?>
                    <button class="md-font btn-grey" onclick="window.location=''" disabled><i class="fa fa-arrow-circle-up"></i> Import</button>
                <?php } ?>
                <?php if($this->ob_LoginAuth->chk_menu_permission('Export_Request_WFA')){ ?>
                    <button class="md-font btn-grey" onclick="window.location='/Download/listexporttoexcel/export_id/19'" ><i class="fa fa-arrow-circle-down"></i> Export</button>
                <?php } ?>
            </div>
            <form class="search" id="search_form" action="" method="post" onsubmit="return check_sub();">
                <input type="hidden" id="hide_del1" name="hide_del1" >
                <input type="hidden" value="<?php print $this->num_row; ?>" id="num_row" name="num_row">
                <input type="hidden" value="<?php print $this->page; ?>" id="page" name="page">
                <input type="hidden" value="<?php print $order_col=$this->order_col; ?>" id="order_col" name="order_col">
                <input type="hidden" value="<?php print $order_typ=$this->order_typ; ?>" id="order_typ" name="order_typ">
                <input type="hidden" id="del_con_global" name="del_con_global" value=""/>
                <input type="text" placeholder="Search" name="quick_search" onKeyPress="do_quick_search(event, this.value);"
                       value="<?php print $this->quick_search; ?>">
            </form>
        </div>


        <table class="table-full" data-tablesaw-mode="stack">
            <thead class="sortable">
            <tr>
                <th><input type="checkbox" id="selecctall"> </th>
                <th><?php print $this->ob_LoginAuth->set_excel_header('ID');?><?php print $this->page_sorting_images['request_id']; ?></th>
                <?php if($this->ses_role==1) { ?>
                    <th><?php print $this->ob_LoginAuth->set_excel_header('Company');?><?php print $this->page_sorting_images['company_name']; ?></th>
                <?php } ?>
                <th><?php print $this->ob_LoginAuth->set_excel_header('From');?><?php print $this->page_sorting_images['rent_from']; ?></th>
                <th><?php print $this->ob_LoginAuth->set_excel_header('To');?><?php print $this->page_sorting_images['rent_to']; ?></th>
                <th><?php print $this->ob_LoginAuth->set_excel_header('Vehicle');?><?php print $this->page_sorting_images['vehicle_id']; ?></th>
                <th><?php print $this->ob_LoginAuth->set_excel_header('Approval');?><?php print $this->page_sorting_images['request_status_id']; ?></th>
                <th><?php print $this->ob_LoginAuth->set_excel_header('Task');?><?php print $this->page_sorting_images['driver_task_id']; ?></th>
                <th><?php print $this->ob_LoginAuth->set_excel_header('Driver');?><?php print $this->page_sorting_images['assigned_driver_1_id']; ?></th>
                <th><?php print $this->ob_LoginAuth->set_excel_header('Status');?><?php print $this->page_sorting_images['driver_status_id']; ?></th>
                <th><?php print $this->ob_LoginAuth->set_excel_header('Customer');?><?php print $this->page_sorting_images['customer_name']; ?></th>
                <?php
                if( $this->ob_LoginAuth->chk_menu_permission('Edit_Request_WFA')
                    || $this->ob_LoginAuth->chk_menu_permission('Delete_Request_WFA'))
                {
                    ?>
                    <th>Manage</th>
                <?php
                }
                ?>


            </tr>
            </thead>
            <tbody>
            <?php
            $sl = 1;
            foreach($this->request_rows as $k=>$v)
            {
                $idd=$v['request_id'];
                ?>
                <tr>
                    <td><input type="checkbox" value='<?php echo $idd;?>' name="chk[]" id="del_con_<?php echo $sl;?>" class="checkbox1"> <?php // print $idd; ?></td>
                    <td>

                        <?php
                        if($this->ob_LoginAuth->chk_menu_permission('Request_Details'))
                        {
                            ?>
                            <a href="/Request/details/idd/<?php echo $v['request_id'];?>">
                                <?php print $this->ob_LoginAuth->set_excel_values($v['req_gen_id'],$idd); ?>
                            </a>
                        <?php
                        }else{  ?>

                            <?php print $this->ob_LoginAuth->set_excel_values($v['req_gen_id'],$idd); ?>
                        <?php
                        }
                        ?>
                    </td>
                    <?php if($this->ses_role==1) { ?>
                        <td><?php print $this->ob_LoginAuth->set_excel_values($v['company_name'],$idd); ?></td>
                    <?php } ?>
                    <td><?php print $this->ob_LoginAuth->set_excel_values(date('M-d-Y g:i A',strtotime($v['rent_from'])),$idd); ?></td>
                    <td><?php print $this->ob_LoginAuth->set_excel_values(date('M-d-Y g:i A',strtotime($v['rent_to'])),$idd); ?></td>
                    <td>
                        <a href="/Vehicles/details/idd/<?php echo $v['vehicle_id'];?>/view/list"><?php print $this->ob_LoginAuth->set_excel_values($v['assigned_vehicle_name'],$idd); ?>
                    </td>
                    <td><?php print $this->ob_LoginAuth->set_excel_values($v['request_status_name'],$idd); ?></td>
                    <td><?php print $this->ob_LoginAuth->set_excel_values($v['driver_task_name'],$idd); ?></td>
                    <td>
                        <?php
                        $driver = $v['driver_task_name']=='Delivery'
                        ||$v['driver_task_name']=='Driver'
                            ? $v['assigned_driver_1_id_name']
                            : $v['assigned_driver_2_id_name'];
                        print $this->ob_LoginAuth->set_excel_values($driver,$idd);
                        ?>
                    </td>
                    <td> <?php print $this->ob_LoginAuth->set_excel_values($v['status_name'],$idd); ?> </td>
                    <td> <?php print $this->ob_LoginAuth->set_excel_values($v['customer_name'],$idd); ?> </td>
                    <?php
                    if( $this->ob_LoginAuth->chk_menu_permission('Edit_Request_WFA')
                    || $this->ob_LoginAuth->chk_menu_permission('Delete_Request_WFA'))
                    {
                    ?>
                    <td>
                        <?php if($this->ob_LoginAuth->chk_menu_permission('Edit_Request_WFA')) {?>
                            <a href="/Request/manage/idd/<?php echo $v['request_id'];?>/page/listwfa" style="<?php echo $edit;?>">Edit</a> &nbsp;&nbsp;
                        <?php } ?>
                        <?php if($this->ob_LoginAuth->chk_menu_permission('Delete_Request_WFA')) {?>
                            <a href="/Request/list/del_id/<?php echo $v['request_id'];?>" style="<?php echo $del;?>"  onclick="return confirm('Are you sure you want to delete?')">Delete</a>
                        <?php } ?>

                    </td>
                    <?php
                    }
                    ?>
                </tr>
                <?php
                $sl++;
            }
            ?>
            <input type="hidden" id="del_con_tcount" value="<?php echo $sl; ?>"/>
            </tbody>
        </table>
        <?php print $this->page_peginetion; ?>

        <!--<div class="content-main transparent right half">
            <button class="btn-grey">Cancel</button>
            <button class="btn-green">Add User</button>
        </div>-->
    </div>
</div>






</div>