<script type="application/javascript">
    function sub_check()  {
        var driver_task_id = $("#driver_task_id").val().trim();
        var customer_name  = $("#customer_name").val().trim();
        var rent_from = $("#rent_from").val().trim();
        var rent_to = $("#rent_to").val().trim();
        var package_id = $("#package_id").val().trim();
        var estimated_price = $("#estimated_price").val().trim();
        var date_error = $("#date_error").val().trim();
        var delivery_address =  $("#delivery_address").val().trim();
        var pickup_address  = $("#pickup_address").val().trim();
        var company = $("#company").val().trim();
        var contact_number = $("#contact_number").val().trim();
        var cust_id = $("#cust_id").val().trim();
        var no_of_days = $("#no_of_days").val().trim();



        var err_vl = '';

        if(!driver_task_id)
        {
            err_vl += '1';
            $("#err_driver_task_id").html("Driver Task is Mandatory.");
        }else{

            if(driver_task_id=='1' || driver_task_id=='3')
            {

                if(!delivery_address)
                {
                    err_vl += '2';
                    $("#err_pickup_address").html("&nbsp;");
                    $("#err_delivery_address").html("Delivery Address is Mandatory.");
                }else{
                    $("#err_delivery_address").html("&nbsp;");
                }


            }else if(driver_task_id=='2')
            {
                if(!pickup_address)
                {
                    err_vl += '3';
                    $("#err_delivery_address").html("&nbsp;");
                    $("#err_pickup_address").html("Pickup Address is Mandatory.");
                }else{
                    $("#err_pickup_address").html("&nbsp;");
                }



            }else{
                $("#err_pickup_address").html("&nbsp;");
                $("#err_delivery_address").html("&nbsp;");
            }
            $("#err_driver_task_id").html("&nbsp;");
        }

        if(!customer_name)
        {
            err_vl += '4';
            $("#err_customer_name").html("Customer Name is Mandatory.");
        }else{
            $("#err_customer_name").html("&nbsp;");
        }




        if(!package_id)
        {
            err_vl += '7';
            $("#err_package_id").html("Package is Mandatory.");
        }else{
            $("#err_package_id").html("&nbsp;");
        }

        if(!package_id)
        {
            err_vl += '8';
            $("#err_package_id").html("Package is Mandatory.");
        }else{
            $("#err_package_id").html("&nbsp;");
        }



        if(!estimated_price || estimated_price==0)
        {
            err_vl += '9';
            $("#err_estimated_price").html("Invalid Estimated Price");
        }else{
            $("#err_estimated_price").html("&nbsp;");
        }

        if(!rent_from)
        {
            err_vl += '10';
            $("#err_rent_from").html("Rent From Mandatory");
        }else{
            $("#err_rent_from").html("&nbsp;");
        }

        if(!rent_to)
        {
            err_vl += '11';
            $("#err_rent_to").html("Rent To Mandatory");
        }else{
            if(date_error == 'Y')
            {
                err_vl += '12';
                $("#err_rent_to").html('Rent To must be equal or greater than Rent From');
            }else{
                $("#err_rent_to").html("&nbsp;");
            }
        }

        if(!package_id)
        {
            err_vl += '13';
            $("#err_package_id").html("Package is Mandatory");
        }else{
            $("#err_package_id").html("&nbsp;");
        }

        if(!company)
        {
            err_vl += '14';
            $("#err_company").html("Company is Mandatory");
        }else{
            $("#err_company").html("&nbsp;");
        }

        var pattern = /^\d+$/;

        if(!cust_id || cust_id=='0')
        {
            if(!contact_number)
            {
                err_vl += '15';
                $("#err_contact_number").html("Contact number is Mandatory");
            }else if(!pattern.test(contact_number)){
                err_vl += '16';
                $("#err_contact_number").html("Contact number must be numeric");
            }else{
                $("#err_contact_number").html("&nbsp;");
            }

        }else{
            $("#err_contact_number").html("&nbsp;");
        }

        if(!no_of_days)
        {
            err_vl += '18';
            $("#err_no_of_days").html("No of days is mandatory");
        }else{
            $("#err_no_of_days").html("&nbsp;");
        }



        if(err_vl!="")
        {return false;}
    }

    function view_image(sl,idd) {
        $.ajax({
            type: 'GET',
            url: "/Request/viewimage/",
            data: { idd: idd }
        }).done(function(data) {
                var t = JSON.parse(data);
                $("#modal-header").html('Image '+sl);
                $("#image-src").attr('src','/public/uploads/request/'+t['image_name']);

            });
    }

    function remove_image(idd,req_id) {

        $.ajax({
            type: 'GET',
            url: "/Request/removeimage/",
            data: { req_id: req_id, idd: idd }
        }).done(function(data) {
                var t = JSON.parse(data);
                alert(t['msg']);
                window.location.href='/Request/manage/idd/'+req_id;
            });
    }

    function callback(){
        var didd = '';
        chk_dates_validate();
        var rent_from = $("#rent_from").val().trim();
        var rent_to = $("#rent_to").val().trim();

        check_available_vehicles(rent_from,rent_to,didd);
        check_available_drivers1(rent_from,rent_to,didd);
        check_available_drivers2(rent_from,rent_to,didd);

        //check_validate_dates(didd);
        var package_id = $("#package_id").val().trim();
        calc_estimated_cost(package_id);
    }

    function chk_dates_validate() {
        var package_id = $("#package_id").val().trim();
        var rent_from = $("#rent_from").val().trim();
        var no_of_days = $("#no_of_days").val().trim();
        var date = new Date(rent_from);
        var newdate = new Date(date);
        newdate.setDate(newdate.getDate() + no_of_days*1);
        var d = newdate.getDate();
        var m = newdate.getMonth() + 1;
        var y = newdate.getFullYear();
        var h = newdate.getHours();
        var n = newdate.getMinutes();

        d = d<10 ? ("0" + d) : d; // day
        m = m<10 ? ("0" + m) : m; // month
        h = h<10 ? ("0" + h) : h; // hour
        n = n<10 ? ("0" + n) : n; // minute
        var rent_to = y+'-'+m+'-'+d+' '+h+':'+n;
        $("#rent_to").val(rent_to);

        if(rent_to && rent_from)
        {
            $.ajax({
                type: 'GET',
                url: "/Request/getestimatedcost/",
                data: { rent_to: rent_to, rent_from: rent_from , package_ : package_id}
            }).done(function(data) {
                $("#estimated_price").val(currency_format(data*1));
                $("#estimated_price_num").val(data);
            });
        }
    }

    function calc_estimated_cost(value) {
        var rent_to = $("#rent_to").val().trim();
        var rent_from = $("#rent_from").val().trim();
        if(rent_to && rent_from)
        {
            $.ajax({
                type: 'GET',
                url: "/Request/getestimatedcost/",
                data: { rent_to: rent_to, rent_from: rent_from , package_ : value}
            }).done(function(data) {
                $("#estimated_price").val(currency_format(data*1));
                $("#estimated_price_num").val(data);
                });
        }

    }

    function check_available_vehicles(rent_from,rent_to,rental_id){
        var html = '<select name="rental_id" id="rental_id">';
        html += '<option value="">Select</option>';

        $.ajax({
            type: 'GET',
            url: "/Request/checkavailabevehicle/",
            data: { rent_from: rent_from , rent_to: rent_to , rental_id:rental_id}
        }).done(function(data) {
                //alert(data);
                var t = JSON.parse(data);
                //alert(t[0].rental_id);

                for(var i=0;i<t.length;i++)
                {
                    html += '<option value="'+ t[i].rental_id+'">'+t[i].assigned_vehicle_name+'</option>';
                }
                //alert(t.length);

                $("#rental_id").html(html);
                $("#rental_id").val(rental_id);
            });
        //$('#rental_id option[value=13]').attr('selected','selected');
    }

    function check_available_drivers1(rent_from,rent_to,didd){
        var html = '<select name="assigned_driver_1_id" id="assigned_driver_1_id">';
        html += '<option value="">Select</option>';
        $.ajax({
            type: 'GET',
            url: "/Request/checkavailabedrivers1/",
            data: { rent_from: rent_from , rent_to: rent_to ,didd:didd }
        }).done(function(data) {
                var t = JSON.parse(data);
                for(var i=0;i<t.length;i++)
                {
                    html += '<option value="'+ t[i].user_id+'">'+t[i].user_full_name+'</option>';
                }
                $("#assigned_driver_1_id").html(html);
                $("#assigned_driver_1_id").val(didd);
            });
        //alert(didd);
        //$("#assigned_driver_1_id").val(didd);
    }

    function check_available_drivers2(rent_from,rent_to,didd){
        var html = '<select name="assigned_driver_2_id" id="assigned_driver_2_id">';
        html += '<option value="">Select</option>';
        $.ajax({
            type: 'GET',
            url: "/Request/checkavailabedrivers2/",
            data: { rent_from: rent_from , rent_to: rent_to ,didd:didd}
        }).done(function(data) {
                var t = JSON.parse(data);
                for(var i=0;i<t.length;i++)
                {
                    html += '<option value="'+ t[i].user_id+'">'+t[i].user_full_name+'</option>';
                }
                $("#assigned_driver_2_id").html(html);
                $("#assigned_driver_2_id").val(didd);

            });
        //$("#assigned_driver_2_id").val(didd);
    }

    function check_vehicle_package_types(rental_id){
        $.ajax({
            type: 'GET',
            url: "/Request/checkvehiclepackagetypes/",
            data: { rental_id:rental_id }
        }).done(function(data) {
            var html = '<select name="package_type_id" id="package_type_id" onchange="calc_estimated_cost(this.value);">';
            html += '<option value="">Select</option>';

            var t = JSON.parse(data);
            for(var i=0; i<t.length; i++) {
                html += '<option value="'+ t[i].package_type_id+'">'+t[i].package_type_name+'</option>';
            }
            $("#package_type_id").html(html);

            var html = '<select name="package_id" id="package_id" onchange="calc_estimated_cost(this.value);">';
            html += '<option value="">Select</option>';
            $("#package_id").html(html);
        });
    }

    function check_package_type_packages(package_type_id){
        $.ajax({
            type: 'GET',
            url: "/Request/checkpackagetypepackages/",
            data: { package_type_id:package_type_id }
        }).done(function(data) {
            var html = '<select name="package_id" id="package_id" onchange="calc_estimated_cost(this.value);">';
            html += '<option value="">Select</option>';
            
            var t = JSON.parse(data);
            for(var i=0; i<t.length; i++) {
                html += '<option value="'+ t[i].package_id+'">'+t[i].package_name+'</option>';
            }

            $("#package_id").html(html);
        });
    }

    function change_validate(value)  {
        if(value=='1' || value=='3')
        {
            $(".dtd").show();
            $(".dtp").hide();
            $("#delivery_address_star").show();
            $("#pickup_address_star").hide();

            $("#assigned_driver_2_id").val("");
            $("#pickup_address").val("");


        }else if(value=='2')
        {
            $(".dtd").hide();
            $(".dtp").show();
            $("#pickup_address_star").show();
            $("#delivery_address_star").hide();
            $("#assigned_driver_1_id").val("");
            $("#delivery_address").val("");

        }else{
            $(".dtd").hide();
            $(".dtp").hide();
            $("#pickup_address_star").hide();
            $("#delivery_address_star").hide();
            $("#assigned_driver_1_id").val("");
            $("#delivery_address").val("");
            $("#assigned_driver_2_id").val("");
            $("#pickup_address").val("");
        }
    }

    function currency_format(n) {
        return n.toFixed(2).replace(/./g, function(c, i, a) {
                return i > 0 && c !== "." && (a.length - i) % 3 === 0 ? "," + c : c;
            });
    }

    function change_date(value) {
        //var no_of_days = $("#no_of_days").val().trim();
        var rent_from = $("#rent_from").val().trim();
        if(rent_from)
        callback();

    }
</script>
<style type="text/css">
    .typeahead {
        background-color: #FFFFFF;

    }
    .typeahead:focus {
        border: 2px solid #0097CF;
    }
    .tt-query {
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
    }
    .tt-hint {
        color: #999999;
    }
    .tt-menu {
        background-color: #FFFFFF;
        border: 1px solid rgba(0, 0, 0, 0.2);
        border-radius: 2px;
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
        margin-top: 12px;
        padding: 8px 0;
        width: 100%;
    }
    .tt-suggestion {
        font-size: 12px;  /* Set suggestion dropdown font size */
        padding: 3px 20px;
    }
    .tt-suggestion:hover {
        cursor: pointer;
        background-color: #0097CF;
        color: #FFFFFF;
    }
    .tt-suggestion p {
        margin: 1;
    }
</style>
<?php
//echo $this->request_detail['assigned_driver_1_id'];
?>

<div class="content-wrapper">
    <h2 class="heading"><?php echo $this->request_detail['request_id'] ? 'Update Request' : 'Add a New Request' ?></h2>
    <div class="content-main full">
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title" id="modal-header"></h4>
                    </div>
                    <div class="modal-body">
                        <p><img id="image-src" src=""></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
        <form class="default-form" action="/Request/submitrequest/" onsubmit="return sub_check();" method="post" enctype="multipart/form-data">
            <input type="hidden" name="em_ex" id="em_ex">
            <input type="hidden" name="idd" id="req_idd" value="<?php echo $this->request_detail['request_id'] ? $this->request_detail['request_id'] : '' ?>">
            <input type="hidden" name="date_error" id="date_error" value="">
            <input type="hidden" name="page" id="page" value="<?php echo $this->page;?>">
            <input type="hidden" name="cust_id" id="cust_id" value="<?php echo $this->request_detail['customer_id'] ? $this->request_detail['customer_id'] : '' ?>">
            <input type="hidden" name="estimated_price_num" id="estimated_price_num" value="<?php echo $this->request_detail['estimated_price'] ? $this->request_detail['estimated_price'] : '' ?>">

            <?php
                if ($this->ses_role != 4) {
                    ?>
                <div class="form-group">
                    <label for="pass2" class="control-label">Driver Task <span class="red">*</span><span class="smalltext required"></label>
                    <div class="input-container">
                        <select name="driver_task_id" id="driver_task_id" onchange="change_validate(this.value)">
                            <option value="">Select</option>
                            <?php foreach ($this->driverTaskList as $k=>$v) {
                        ?>
                                <option value="<?php echo $v['driver_task_id']; ?>"
                                    <?php if ($v['driver_task_id']==$this->request_detail['driver_task_id']) {
                            echo 'selected';
                        } ?>><?php echo $v['driver_task_name']; ?></option>
                            <?php
                    } ?>

                        </select>
                        <span class="error" id="err_driver_task_id">&nbsp;</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="uid">Customer Name: <span class="red">*</span><br></label>
                    <div class="input-container">
                        <input placeholder="Customer Name" id="customer_name" name="customer_name" onblur="get_id(this.value)" value="<?php echo $this->request_detail['customer_name'] ? $this->request_detail['customer_name'] : '' ?>"/>
                       <span class="error" id="err_customer_name">&nbsp;</span>
                    </div>
                </div>
                <div class="form-group" id="contact_no_div">
                    <label for="uid">Contact Number: <span class="red">*</span><br></label>
                    <div class="input-container">
                        <input placeholder="Contact Number" id="contact_number" name="contact_number"  value=""/>
                        <span class="error" id="err_contact_number">&nbsp;</span>
                    </div>
                </div>
                <div class="form-group" id="no_of_passengers_div">
                    <label for="uid">No. of Passengers:<br></label>
                    <div class="input-container">
                        <input placeholder="No of Passengers" id="no_of_passengers" name="no_of_passengers"  value=""/>
                        <span class="error" id="err_no_of_passengers">&nbsp;</span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="pass2" class="control-label">No. of Days <span class="red">*</span></label>
                    <div class="input-container">
                        <input class="form-control text-center" id="no_of_days" name="no_of_days" autocomplete="off" onkeyup="change_date();" onchange="change_date();" value="<?php echo $this->request_detail['no_of_days'] ? $this->request_detail['no_of_days'] : $this->no_of_days ?>"   data-rule="requested"  type="number" min="0" >
                        <span class="error" id="err_no_of_days">&nbsp;</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="uid">Rent From: <span class="red">*</span><br></label>
                    <div class="input-container">
                        <div class="input-group date form_datetime col-md-8" id="rent_from_div">
                            <input class="form-control" placeholder="Rent From" type="text" id="rent_from" name="rent_from"  onblur="chk_dates_validate()" value="<?php echo $this->request_detail['rent_from'] ? $this->request_detail['rent_from'] : $this->from ?>">
                            <span class="input-group-addon"><i class="fa fa-times" aria-hidden="true"></i></span>
                            <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
                        </div>
                       <span class="error" id="err_rent_from">&nbsp;</span>
                    </div>
                </div>

                <!--<div class="form-group">
                    <label for="uid">Rent To: <span class="red">*</span><br></label>
                    <div class="input-container">
                        <div class="input-group date form_datetime col-md-8" id="rent_to_div">
                            <input class="form-control" placeholder="Rent To" type="text" id="rent_to" name="rent_to" onblur="chk_dates_validate()"  value="<?php /*echo $this->request_detail['rent_to'] ? $this->request_detail['rent_to'] : '' */?>">
                            <span class="input-group-addon"><i class="fa fa-times" aria-hidden="true"></i></span>
                            <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
                        </div>
                        <span class="error" id="err_rent_to">&nbsp;</span>
                    </div>
                </div>-->

                <div class="form-group">
                    <label for="uid">Rent To: <span class="red">*</span><br></label>
                    <div class="input-container">
                            <input class="form-control" placeholder="Rent To" readonly type="text" id="rent_to" name="rent_to" value="<?php echo $this->request_detail['rent_to'] ? $this->request_detail['rent_to'] : $this->to ?>">
                        <span class="error" id="err_rent_to">&nbsp;</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="pass2" class="control-label">Vehicle <span class="smalltext required"></label>
                    <div class="input-container">
                        <select name="rental_id" id="rental_id" onchange="check_vehicle_package_types(this.value);">
                            <option value="">Select</option>
                            <?php foreach ($this->assignedVehicleList as $k=>$v) {
                        ?>
                                <option value="<?php echo $v['rental_id']; ?>"
                                    <?php echo(($this->request_detail['vehicle_id'] == $v['rental_id']) ? "Selected" :(($this->rentid == $v['rental_id']) ? "Selected" :" ")); ?>><?php echo $v['assigned_vehicle_name']; ?></option>
                            <?php
                    } ?>

                        </select>
                        <span class="error" id="err_rental_id">&nbsp;</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="pass2" class="control-label">Package Type <span class="smalltext required"></label>
                    <div class="input-container">
                        <select name="package_type_id" id="package_type_id" onchange="check_package_type_packages(this.value);">
                            <option value="">Select</option>
                            <?php foreach ($this->packageTypeList as $k=>$v) {
                        ?>
                                <option value="<?php echo $v['package_type_id']; ?>"
                                    <?php if ($v['package_type_id']==$this->request_detail['package_type_id']) {
                            echo 'selected';
                        } ?>><?php echo $v['package_type_name']; ?></option>
                            <?php
                    } ?>
                        </select>
                        <span class="error" id="err_package_type_id">&nbsp;</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="pass2" class="control-label">Package <span class="red">*</span><span class="smalltext required"></label>
                    <div class="input-container">
                        <select name="package_id" id="package_id" onchange="calc_estimated_cost(this.value);">
                            <option value="">Select</option>
                            <?php foreach ($this->packageList as $k=>$v) {
                        ?>
                                <option value="<?php echo $v['package_id']; ?>"
                                    <?php if ($v['package_id']==$this->request_detail['package_id']) {
                            echo 'selected';
                        } ?>><?php echo $v['package_name']; ?></option>
                            <?php
                    } ?>

                        </select>
                        <span class="error" id="err_package_id">&nbsp;</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="uid">Estimated Price: <span class="red">*</span><br></label>
                    <div class="input-container">
                        <input type="text" placeholder="Estimated Price" id="estimated_price"  name="estimated_price" value="<?php echo $this->request_detail['estimated_price'] ? number_format($this->request_detail['estimated_price'], 2, '.', ',') : '' ?>" readonly>
                        <span class="error" id="err_estimated_price">&nbsp;</span>

                    </div>
                </div>
                <?php if ($_SESSION['tranzgo_session']['account_id']==1) {
                        ?>
                    <div class="form-group">
                        <label for="pass2" class="control-label">Company <span class="red">*</span></label>
                        <div class="input-container">
                            <select name="company" id="company">
                                <option value="">Select</option>
                                <?php foreach ($this->companyList as $k=>$v) {
                            ?>
                                    <option value="<?php echo $v['company_id']; ?>"
                                        <?php if ($v['company_id']==$this->request_detail['company_id']) {
                                echo 'selected';
                            } ?>><?php echo $v['company_name']; ?></option>
                                <?php
                        } ?>
                            </select>
                            <span class="error" id="err_company">&nbsp;</span>
                        </div>
                    </div>
                <?php
                    } else {
                        ?>
                    <div class="form-group">
                        <label for="pass2" class="control-label">Company <span class="red">*</span></label>
                        <div class="input-container">
                            <select name="company" id="company">
                                <option value="<?php echo $this->getCompanyBySessId['company_id']; ?>"><?php echo $this->getCompanyBySessId['company_name']; ?></option>
                            </select>
                            <span class="error" id="err_company">&nbsp;</span>
                        </div>
                    </div>
                <?php
                    } ?>

                <div class="form-group dtd">
                    <label for="uid">Delivery Address: <span class="red" id="delivery_address_star">*</span><br></label>
                    <div class="input-container">
                        <textarea class="form-control" placeholder="Delivery Address" id="delivery_address"  name="delivery_address"><?php echo $this->request_detail['delivery_address'] ? $this->request_detail['delivery_address'] : '' ?></textarea>
                        <span class="error" id="err_delivery_address">&nbsp;</span>

                    </div>
                </div>

                <div class="form-group dtd">
                    <label for="uid">Assigned Driver 1: <span class="red" id="assigned_driver1_star">*</span><br></label>
                    <div class="input-container">
                        <select id="assigned_driver_1_id"  name="assigned_driver_1_id">
                            <option value="">Select</option>
                            <?php foreach ($this->driverList as $k=>$v) {
                        ?>
                                <option value="<?php echo $v['user_id']; ?>"
                                    <?php if ($v['user_id']==$this->request_detail['assigned_driver_1_id']) {
                            echo 'selected';
                        } ?>><?php echo $v['user_full_name']; ?></option>
                            <?php
                    } ?>

                        </select>

                        <span class="error" id="err_assigned_driver_1_id">&nbsp;</span>

                    </div>
                </div>

                <div class="form-group dtp">
                    <label for="uid">Pickup Address: <span class="red" id="pickup_address_star">*</span><br></label>
                    <div class="input-container">
                        <textarea class="form-control" placeholder="Pickup Address" id="pickup_address"  name="pickup_address"><?php echo $this->request_detail['pickup_address'] ? $this->request_detail['pickup_address'] : '' ?></textarea>
                        <span class="error" id="err_pickup_address">&nbsp;</span>

                    </div>
                </div>

                <div class="form-group dtp">
                    <label for="uid">Assigned Driver 2: <span class="red" id="assigned_driver2_star">*</span><br></label>
                    <div class="input-container">
                        <select id="assigned_driver_2_id"  name="assigned_driver_2_id">
                            <option value="">Select</option>
                            <?php foreach ($this->driverList as $k=>$v) {
                        ?>
                                <option value="<?php echo $v['user_id']; ?>"
                                    <?php if ($v['user_id']==$this->request_detail['assigned_driver_2_id']) {
                            echo 'selected';
                        } ?>><?php echo $v['user_full_name']; ?></option>
                            <?php
                    } ?>

                        </select>

                        <span class="error" id="err_assigned_driver_2_id">&nbsp;</span>

                    </div>
                </div>

                <div class="form-group">
                    <label for="uid">Payment Method: <br></label>
                    <div class="input-container">
                        <select name="payment_method_id" id="payment_method_id">
                            <?php foreach ($this->paymentMethod as $k=>$v) {
                        ?>
                                <option value="<?php echo $v['payment_method_id']; ?>"
                                    <?php if ($v['payment_method_id']==$this->request_detail['payment_method_id']) {
                            echo 'selected';
                        } ?>><?php echo $v['payment_method_name']; ?></option>
                            <?php
                    } ?>
                        </select>
                        <span class="error" id="err_payment_method_id">&nbsp;</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="uid">Other Details: <br></label>
                    <div class="input-container">
                        <textarea class="form-control" placeholder="Notes" id="note"  name="note"><?php echo $this->request_detail['note'] ? $this->request_detail['note'] : '' ?></textarea>
                        <span class="error" id="err_note">&nbsp;</span>

                    </div>
                </div>
                <div class="form-group">
                    <label for="uid">Itinerary: <br></label>
                    <div class="input-container">
                        <textarea class="form-control" placeholder="Itinerary" id="itinerary"  name="itinerary"><?php echo $this->request_detail['itinerary'] ? $this->request_detail['itinerary'] : '' ?></textarea>
                        <span class="error" id="err_itinerary">&nbsp;</span>
                    </div>
                </div>
            <?php
                }
            ?>

            <div class="form-group">
                <label for="uid">Image 1: <br></label>
                <div class="input-container">
                    <input type="file"  name="image[]">

                </div>
            </div>
            <div class="form-group">
                <label for="uid">Image 2: <br></label>
                <div class="input-container">
                    <input type="file" name="image[]">

                </div>
            </div>
            <div class="form-group">
                <label for="uid">Image 3: <br></label>
                <div class="input-container">
                    <input type="file"  name="image[]">

                </div>
            </div>
            <div class="form-group">
                <label for="uid">Image 4: <br></label>
                <div class="input-container">
                    <input type="file" name="image[]">

                </div>
            </div>
            <?php
            if (count($this->request_images) > 0) {
                $sl=1;
                foreach ($this->request_images as $k=>$v) {
                    ?>


            <div class="col-md-2">
                <a href="javascript:remove_image(<?php echo $v['request_image_id']; ?>,<?php echo $this->request_detail['request_id']; ?>)" onclick="return confirm('Are you sure you want to delete?')" ><i class="fa fa-times" aria-hidden="true"></i> </a>
                <div class="thumbnail">

                    <a href="javascript:void(0)" onclick="view_image(<?php echo $sl; ?>,<?php echo $v['request_image_id']; ?>);"  data-toggle="modal" data-target="#myModal">
                        <img src="/public/uploads/request/<?php echo $v['image_name']; ?>" alt="Moustiers Sainte Marie" style="width:100%;height: 100px;">
                        <div class="caption">
                            <p>Image <?php echo $sl; ?> </p>
                        </div>
                    </a>
                </div>
            </div>
            <?php
                $sl++;
                }
            }
            ?>
            <!-- Modal -->


            <div class="group">
                <button type="button" onclick="cancel('<?php echo $this->cancel_link?>');" class="btn-grey">Cancel</button>
                <button type="submit" class="btn-green"><?php echo $this->request_detail['request_id'] ? 'Update Request' : 'Add Request' ?></button>
            </div>
        </form>
    </div>
</div>

