<script type="application/javascript">

    function sub_check()
    {
        var idd = $("#idd").val().trim();


        var company_id=$("#company_id").val().trim();
        var assigned_vehicle_name=$("#assigned_vehicle_name").val().trim();
        var vehicle_type_id = $("#vehicle_type_id").val().trim();
        var max_passenger=$("#max_passenger").val().trim();
        var transmission_id=$("#transmission_id").val().trim();
        var plt_exist=$("#plt_exist").val().trim();



        var err_vl="";


        if(!company_id)
        {
            err_vl+="1";
            $("#err_company_id").html("Company is Mandatory");
        }else{
            $("#err_company_id").html("&nbsp;");
        }

        if(!ValidateFname(assigned_vehicle_name))
        {
            err_vl+="2";
            $("#err_assigned_vehicle_name").html("Plate No must be at least 2 character long");
        }else if(plt_exist > 0){
            err_vl+="3";
            $("#err_assigned_vehicle_name").html("Plate No already exist");
        }else{
            $("#err_assigned_vehicle_name").html("&nbsp;");
        }


        if(!vehicle_type_id){
            err_vl+="4";
            $("#err_vehicle_type_id").html("Vehicle type is Mandatory");
        }
        else{
            $("#err_vehicle_type_id").html("&nbsp;");
        }

        if(!max_passenger){
            err_vl+="5";
            $("#err_max_passenger").html("Max Passengers is Mandatory");
        }
        else{
            $("#err_max_passenger").html("&nbsp;");
        }

        if(!transmission_id){
            err_vl+="6";
            $("#err_transmission_id").html("Transmission is Mandatory");
        }
        else{
            $("#err_transmission_id").html("&nbsp;");
        }

        if(err_vl!="")
        {return false;}

    }


    function check_plate_no(value)
    {
        var idd = $("#idd").val().trim();
        $.ajax({
            type: 'GET',
            url: "/Vehicles/checkplateno/",
            data: { Plate_no: value , idd: idd }
        }).done(function(data) {
                if(data > 0)
                {
                    $("#plt_exist").val('1');
                }else{
                    $("#plt_exist").val('0');
                }
            });
    }

    function view_image(sl,idd)
    {
        $.ajax({
            type: 'GET',
            url: "/Vehicles/viewimage/",
            data: { idd: idd }
        }).done(function(data) {

                var t = JSON.parse(data);
                $("#modal-header").html('Image '+sl);
                $("#image-src").attr('src','/public/uploads/rental/'+t['image_name']);

            });
    }

    function remove_image(rental_images_id,rental_id)
    {

        $.ajax({
            type: 'GET',
            url: "/Vehicles/removeimage/",
            data: { rental_images_id: rental_images_id, rental_id: rental_id }
        }).done(function(data) {
                var t = JSON.parse(data);
                alert(t['msg']);

                window.location.href='/Vehicles/manage/idd/'+rental_id;


            });
    }




</script>
<style type="text/css">


    .typeahead {
        background-color: #FFFFFF;

    }
    .typeahead:focus {
        border: 2px solid #0097CF;
    }
    .tt-query {
        box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset;
    }
    .tt-hint {
        color: #999999;
    }
    .tt-menu {
        background-color: #FFFFFF;
        border: 1px solid rgba(0, 0, 0, 0.2);
        border-radius: 2px;
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
        margin-top: 12px;
        padding: 8px 0;
        width: 100%;
    }
    .tt-suggestion {
        font-size: 12px;  /* Set suggestion dropdown font size */
        padding: 3px 20px;
    }
    .tt-suggestion:hover {
        cursor: pointer;
        background-color: #0097CF;
        color: #FFFFFF;
    }
    .tt-suggestion p {
        margin: 1;
    }
</style>
<?php
$array_max_passenger = array(1=>'1 - 4',2=>'4 - 7',3=>'8 - 11');

?>
<div class="content-wrapper">
    <h2 class="heading"><?php echo $this->rental_detail['rental_id'] ? 'Update Vehicle' : 'Add a New Vehicle' ?></h2>
    <div class="content-main full">


        <form class="default-form" action="/Vehicles/submitrequest/" onsubmit="return sub_check();" method="post" enctype="multipart/form-data">
        <input type="hidden" name="idd" id="idd" value="<?php echo $this->rental_detail['rental_id'] ? $this->rental_detail['rental_id'] : '' ?>">
        <input type="hidden" name="plt_exist" id="plt_exist" value="">

        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title" id="modal-header"></h4>
                    </div>
                    <div class="modal-body">
                        <p><img id="image-src" src=""></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>

        <?php if($_SESSION['tranzgo_session']['account_id']==1) { ?>
            <div class="form-group">
                <label for="pass2" class="control-label">Owner <span class="red">*</span></label>
                <div class="input-container">
                    <select name="company_id" id="company_id">
                        <option value="">Select</option>
                        <?php foreach($this->companyList as $k=>$v){?>
                            <option value="<?php echo $v['company_id']; ?>"
                                <?php if($v['company_id']==$this->rental_detail['company_id']){ echo 'selected';} ?>><?php echo $v['company_name']; ?></option>
                        <?php }?>
                    </select>
                    <span class="error" id="err_company_id">&nbsp;</span>
                </div>
            </div>
        <?php }else {  ?>
            <div class="form-group">
                <label for="pass2" class="control-label">Owner <span class="red">*</span></label>
                <div class="input-container">
                    <select name="company_id" id="company_id">
                        <option value="<?php echo $this->getCompanyBySessId['company_id']; ?>"><?php echo $this->getCompanyBySessId['company_name']; ?></option>
                    </select>
                    <span class="error" id="err_company_id">&nbsp;</span>
                </div>
            </div>
        <?php  } ?>

            <div class="form-group">
                <label for="pass2" class="control-label">Garage <span class="smalltext required"></label>
                <div class="input-container">
                    <select name="garage_type_id" id="garage_type_id">
                        <option value="">Select</option>
                        <?php
                        foreach($this->garage_types as $k=>$v)
                        {
                            ?>
                            <option value="<?php echo $v['garage_type_id'];?>"
                                <?php if($v['garage_type_id']==$this->rental_detail['garage_type_id']){ echo 'selected';} ?>
                                ><?php echo $v['garage_type_name'];?></option>
                        <?php
                        }
                        ?>

                    </select>
                    <span class="error" id="err_type">&nbsp;</span>
                </div>
            </div>

            <div class="form-group">
                <label for="pass2" class="control-label">Plate No <span class="red">*</span><span class="smalltext required"></label>
                <div class="input-container">
                    <input type="text" placeholder="Plate No" id="assigned_vehicle_name" name="assigned_vehicle_name" onblur="return check_plate_no(this.value);" value="<?php echo $this->rental_detail['assigned_vehicle_name'] ? $this->rental_detail['assigned_vehicle_name'] : '' ?>">
                    <span class="error" id="err_assigned_vehicle_name">&nbsp;</span>
                </div>
            </div>



            <div class="form-group">
                <label for="pass2" class="control-label">Type <span class="smalltext required"></label>
                <div class="input-container">
                    <select name="vehicle_type_id" id="vehicle_type_id">
                        <option value="">Select</option>
                        <?php foreach($this->vehicleTypeList as $k=>$v){?>
                            <option value="<?php echo $v['vehicle_type_id']; ?>"
                                <?php if($v['vehicle_type_id']==$this->rental_detail['vehicle_type_id']){ echo 'selected';} ?>><?php echo $v['vehicle_type_name']; ?></option>
                        <?php }?>
                    </select>
                    <span class="error" id="err_type">&nbsp;</span>
                </div>
            </div>


            <div class="form-group">
                <label for="pass2" class="control-label">Max Passengers <span class="red">*</span><span class="smalltext required"></label>
                <div class="input-container">
                    <select name="max_passenger" id="max_passenger">
                        <option value="">Select</option>
                        <?php
                        foreach($this->vehicle_max_passenger as $k=>$v)
                        {
                         ?>
                            <option value="<?php echo $v['max_passenger'];?>" <?php if($this->rental_detail['max_passenger']==$v['max_passenger']){ echo 'selected';} ?>><?php echo $v['max_passenger_values'];?></option>
                        <?php } ?>
                    </select>
                    <span class="error" id="err_max_passenger">&nbsp;</span>
                </div>
            </div>

            <div class="form-group">
                <label for="pass2" class="control-label">Transmission <span class="red">*</span><span class="smalltext required"></label>
                <div class="input-container">
                    <select name="transmission_id" id="transmission_id">
                        <option value="">Select</option>
                        <?php foreach($this->transmissionList as $k=>$v){?>
                            <option value="<?php echo $v['transmission_id']; ?>"
                                <?php if($v['transmission_id']==$this->rental_detail['transmission_id']){ echo 'selected';} ?>><?php echo $v['transmission_name']; ?></option>
                        <?php }?>
                    </select>
                    <span class="error" id="err_transmission_id">&nbsp;</span>
                </div>
            </div>



            <div class="form-group">
                <label for="uid">Make: <br></label>
                <div class="input-container">
                    <input type="text" placeholder="Make" id="make" name="make" value="<?php echo $this->rental_detail['make'] ? $this->rental_detail['make'] : '' ?>">
                    <span class="error" id="err_make">&nbsp;</span>

                </div>
            </div>
            <div class="form-group">
                <label for="uid">Model: <br></label>
                <div class="input-container">
                    <input type="text" placeholder="Model" id="model" name="model" value="<?php echo $this->rental_detail['model'] ? $this->rental_detail['model'] : '' ?>">
                    <span class="error" id="err_model">&nbsp;</span>

                </div>
            </div>
            <div class="form-group">
                <label for="uid">Year: <br></label>
                <div class="input-container">
                    <input type="text" placeholder="Year" id="year"  name="year" value="<?php echo $this->rental_detail['year'] ? $this->rental_detail['year'] : '' ?>">
                    <span class="error" id="err_year">&nbsp;</span>

                </div>
            </div>
            <div class="form-group">
                <label for="uid">Color: <br></label>
                <div class="input-container">
                    <input type="text" placeholder="Color" id="color"  name="color" value="<?php echo $this->rental_detail['color'] ? $this->rental_detail['color'] : '' ?>">
                    <span class="error" id="err_color">&nbsp;</span>

                </div>
            </div>

            <div class="form-group">
                <label for="pass2" class="control-label">Times Rented <span class="smalltext required"></label>
                <div class="input-container">

                            <div class="input-group spinner col-md-4" data-trigger="spinner">
                                <input class="form-control text-center" id="times_rented" name="times_rented" value="<?php echo $this->rental_detail['times_rented'] ? $this->rental_detail['times_rented'] : 0 ?>"  data-rule="rentaltimerented" type="text" readonly >
                                <div class="input-group-addon">
                                    <a href="javascript:void(0)" class="spin-up" data-spin="up"><i class="fa fa-caret-up"></i></a>
                                    <a href="javascript:void(0)" class="spin-down" data-spin="down"><i class="fa fa-caret-down"></i></a>
                                </div>
                            </div>
                    <span class="error" id="err_times_rented">&nbsp;</span>
                </div>
            </div>

            <div class="form-group">
                <label for="pass2" class="control-label">Status <span class="smalltext required"></label>
                <div class="input-container">
                    <select name="rental_status" id="rental_status">
                        <option value="">Select</option>
                        <option value="1" <?php if($this->rental_detail['rental_status']==1 || !$this->rental_detail['rental_id']){ echo 'selected';} ?>>Active</option>
                        <option value="0" <?php if($this->rental_detail['rental_status']==0 && $this->rental_detail['rental_id']){ echo 'selected';} ?>>Down</option>
                    </select>
                    <span class="error" id="err_status">&nbsp;</span>
                </div>
            </div>


            <div class="form-group">
                <label for="uid">Image 1: <br></label>
                <div class="input-container">
                    <input type="file"  name="image[]">

                </div>
            </div>
            <div class="form-group">
                <label for="uid">Image 2: <br></label>
                <div class="input-container">
                    <input type="file" name="image[]">

                </div>
            </div>
            <div class="form-group">
                <label for="uid">Image 3: <br></label>
                <div class="input-container">
                    <input type="file"  name="image[]">

                </div>
            </div>
            <div class="form-group">
                <label for="uid">Image 4: <br></label>
                <div class="input-container">
                    <input type="file" name="image[]">

                </div>
            </div>
            <?php
            if(count($this->rental_images) > 0)
            {
            $sl=1;
            foreach($this->rental_images as $k=>$v)
            {
            ?>


            <div class="col-md-2">
                <a href="javascript:remove_image(<?php echo $v['rental_images_id'];?>,<?php echo $v['rental_id'];?>)" onclick="return confirm('Are you sure you want to delete?')" ><i class="fa fa-times" aria-hidden="true"></i> </a>
                <div class="thumbnail">

                    <a href="javascript:void(0)" onclick="view_image(<?php echo $sl;?>,<?php echo $v['rental_images_id'];?>);"  data-toggle="modal" data-target="#myModal">
                        <img src="/public/uploads/rental/<?php echo $v['image_name'];?>" alt="Moustiers Sainte Marie" style="width:100%;height: 100px;">
                        <div class="caption">
                            <p>Image <?php echo $sl;?> </p>
                        </div>
                    </a>
                </div>
            </div>
            <?php
                $sl++;
            }
            }
            ?>
            <!-- Modal -->


            <div class="group">
                <button type="button" onclick="cancel('<?php echo $this->cancel_link?>');" class="btn-grey">Cancel</button>
                <button type="submit" class="btn-green"><?php echo $this->rental_detail['rental_id'] ? 'Update Vehicle' : 'Add Rental' ?></button>
            </div>
        </form>
    </div>
</div>
