<div class="content-wrapper">
    <h2 class="heading">Add a New User</h2>
    <div class="content-main full">
        <form class="default-form">
            <div class="form-group">
                <label for="uid">User ID: <br> <span class="smalltext">Use your email address</span></label>
                <div class="input-container">
                    <input type="email"  id="uid" placeholder="Email Address">
                </div>
            </div>
            <div class="form-group">
                <label for="pass1">Password: <br> <span class="smalltext">Minimum of 6 characters</span></label>
                <div class="input-container">
                    <input type="password"  id="pass1" placeholder="****">
                </div>
            </div>
            <div class="form-group">
                <label for="pass2" class="control-label">Confirm Password</label>
                <div class="input-container">
                    <input type="password"  id="pass1" placeholder="****">
                    <span class="error">Password does not match</span>
                </div>
            </div>
            <div class="spacer"></div>
            <div class="form-group">
                <label class="control-label">Name</label>
                <div class="input-container-half">
                    <input type="password" placeholder="First Name">
                </div>
                <div class="input-container-half">
                    <input type="password" placeholder="Last Name">
                </div>
            </div>
            <div class="form-group">
                <label for="pass2" class="control-label">Access Group</label>
                <div class="input-container">
                    <select >
                        <option>System Admin</option>
                        <option>System Admin</option>
                        <option>System Admin</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="pass2" class="control-label">Access Level</label>
                <div class="input-container">
                    <select >
                        <option>Member</option>
                        <option>Member</option>
                        <option>Member</option>
                    </select>
                </div>
            </div>
            <div class="group">
                <button type="button" class="btn-grey">Cancel</button>
                <button type="submit" class="btn-green">Add User</button>
            </div>
        </form>
    </div>
</div>