<script type="application/javascript">
    function reset_pass()
    {
        //alert('aa');
        var ulf_email=$("#ulr_mail").val().trim();

        var chk=1;
        var error_str="";
        if (!ValidateEmail(ulf_email))
        {
            error_str="Give A valid email id";
            chk=0;
        }
        if(error_str!="")
        {
            $("#reset_error").html(error_str);
            $("#demo-resetpassword-success").attr('class', 'alert fail')
            $('#demo-resetpassword-success').slideDown();
        }
        else
        {
            $.ajax({
                url: "/index/resetpass",
                data: { ulf_email: ulf_email }
            }).done(function(data) {
                    //alert(data);
                    if(data*1)
                    {
                        alert("An email for password reset instruction has been sent to '"+ulf_email+"'. Please check your mailbox and remember to check the spam folder too.");
                    }
                    else
                    {
                        alert('E-mail is not present in our database please Register');
                    }

                });
        }

    }
function check_sub()
    {
        //
		var ch_fname=$("#ul_fname").val().trim();
        var ch_lname=$("#ul_lname").val().trim();
        var ch_email=$("#rul_mail").val().trim();
        var is_email_present=$("#is_email_present").val()*1;
        var new_pass=$("#rul_pass").val().trim();
        var re_new_pass=$("#re_ul_pass").val().trim();

//alert(ch_email);

        if(ch_email=='')
        {
            alert("Give a valid email");
            return false;
        }
        if(!ValidateEmail(ch_email))
        {
            alert("Give a valid email");
            return false;
        }
		if(is_email_present)
        {
            alert("E-mail has already been registered");
            return false;
        }

        if(!new_pass)
        {
            alert("Please give a new password");
            return false;
        }
        if(new_pass!=re_new_pass)
        {
            alert("Retype Password dosen't matched");
            return false;
        }
        if(!ValidateFname(ch_fname))
        {
            alert("Give minimum 2 character in First name;");
            return false;
        }
        if(!ValidateLname(ch_lname))
        {
            alert("Give minimum 2 character in Last name;");
            return false;
        }
		//alert('all ok');return false;
    }

    function check_email(p_email)
    {
        $.ajax({
            url: "/index/dupemail",
            data: { U_email: p_email }
        }).done(function(data) {
                //alert(data);
                $("#is_email_present").val(data);
            });
    }

	function clear_msg_center(p)
    {
        if(p)
        {
            $("#msg_center").fadeOut(1000);
        }
        else
        {
            $("#msg_center").fadeOut(300);
            $("#msg_center").fadeIn(300);
            $("#msg_center").fadeOut(300);
            $("#msg_center").fadeIn(300);
            $("#msg_center").fadeOut(300);
            $("#msg_center").fadeIn(300);
            setTimeout('clear_msg_center(1)',5000);
        }

        //
        //document.getElementById('msg_center').innerHTML="&nbsp;";
    }
    setTimeout('clear_msg_center(0)',10000);

    function show_reset()
    {
        $("#lodin_div").hide();
        $("#reset_pass").show();
    }
function show_login()
{
    $("#reset_pass").hide();
    $("#lodin_div").show();
}
</script>

    <div class="row login-container column-seperation">
        <div class="col-md-5 col-md-offset-1" id="reset_pass" style="display: none;">
                <div class="row">
                    <div class="form-group col-md-10">
                        <label class="form-label">Email</label>
                        <div class="controls">
                            <div class="input-with-icon  right">
                                <i class=""></i>
                                <input type="text" name="ulr_mail" id="ulr_mail" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="control-group  col-md-10">
                        <div class="checkbox checkbox check-success" >
                            <a style="cursor: pointer;" onclick="show_login();">Goto Login</a>
                            &nbsp;&nbsp;
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10">
                        <button class="btn btn-primary btn-cons pull-right" type="button" onclick="reset_pass();">Reset Password</button>
                    </div>
                </div>
        </div>
        <div class="col-md-5 col-md-offset-1" id="lodin_div">
            <form id="login-form" class="login-form" action="/index/loginauth" method="post">
                <div class="row">
                    <div class="form-group col-md-10">
                        <label class="form-label">Email</label>
                        <div class="controls">
                            <div class="input-with-icon  right">
                                <i class=""></i>
                                <input type="text" name="ul_mail" id="ul_mail" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-10">
                        <label class="form-label">Password</label>
                        <span class="help"></span>
                        <div class="controls">
                            <div class="input-with-icon  right">
                                <i class=""></i>
                                <input type="password" name="ul_pass" id="ul_pass" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="control-group  col-md-10">
                        <div class="checkbox checkbox check-success" > <a style="cursor: pointer;" onclick="show_reset();">Trouble login in?</a>&nbsp;&nbsp;
                            <input type="checkbox" id="ul_remember" name="ul_remember" value="1">
                            <label for="ul_remember">Keep me reminded </label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <div id="msg_center"><?php print $this->server_msg; ?></div>
                    </div>
                    <div class="col-md-5">
                        <button class="btn btn-primary btn-cons pull-right" type="submit">Login</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-5 ">
            <form id="login-form" class="login-form" action="/index/signup" method="post" onSubmit="return check_sub();">
            <input type="hidden" id="is_email_present" value="0">
                <div class="row">
                    <div class="form-group col-md-10">
                        <label class="form-label">&nbsp;</label>
                        <div class="controls">
                            <div class="input-with-icon  right">
                                <i class=""></i>
                                <input placeholder="Email" type="text" name="rul_mail" id="rul_mail" class="form-control" onkeyup="check_email(this.value);" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-10">
                        <div class="controls">
                            <div class="input-with-icon  right">
                                <i class=""></i>
                                <input placeholder="Password" type="password" name="rul_pass" id="rul_pass" class="form-control" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-10">
                        <div class="controls">
                            <div class="input-with-icon  right">
                                <i class=""></i>
                                <input placeholder="Re-type Password" type="password" name="re_ul_pass" id="re_ul_pass" class="form-control" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-10">
                    	<div class="controls">
                            <div class="input-with-icon  right">
                                <i class=""></i>
                                <input placeholder="First Name" type="password" name="ul_fname" id="ul_fname" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-10">
                        <div class="controls">
                            <div class="input-with-icon  right">
                                <i class=""></i>
                                <input placeholder="Last Name" type="password" name="ul_lname" id="ul_lname" class="form-control">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10">
                        <button class="btn btn-primary btn-cons pull-right" type="submit">Register</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
