<link href="<?php print $this->site_asset; ?>css/font-awesome.min.css" rel="stylesheet">
<link href="<?php print $this->site_asset; ?>css/bootstrap.min.css" rel="stylesheet">
<link href="<?php print $this->site_asset; ?>css/bootstrap-datetimepicker.min.css" rel="stylesheet">
<link href="<?php print $this->site_asset; ?>css/bootstrap-spinner.css" rel="stylesheet">
<link href="<?php print $this->site_asset; ?>css/bootstrap-switch.css" rel="stylesheet">
<link href="<?php print $this->site_asset; ?>css/style.css" rel="stylesheet">
<link href="<?php print $this->site_asset; ?>css/datepicker.css" rel="stylesheet">
<link href="<?php print $this->site_asset; ?>css/easy-autocomplete.min.css" rel="stylesheet">

