<?php
$user_details=$this->user_rows;
?>
<script src="<?php echo $this->site_asset ;?>js/defined_list_fucntions.js"></script>
<script type="application/javascript">
    function check_sub()
    {
        //alert('all done');return false;
    }
    function del_row(idd,nnme)
    {
        if(confirm('Are You Sure to Delete user ('+nnme+')'))
        {
            $("#del_id").val(idd);
            $("#search_form").submit();
        }
    }
    function active_row(idd,nnme,ttype)
    {
        var sstr=(ttype*1)?"Un-lock":"Lock";
        if(confirm('Are You Sure to '+sstr+' user ('+nnme+')'))
        {
            $("#act_id").val(idd);
            $("#act_type").val(ttype);
            $("#search_form").submit();
        }
    }

	function del_con_checkit()
	{
		var valid = '';
		var val = [];
		$(':checkbox:checked').each(function(i){
			val[i] = $(this).val();
		});

		if(confirm("Are you sure you want to delete?"))
		{
			$.ajax({
				type: 'POST',
				url: "/request/mutideleterequest/",
				data: { del_ids: val }
			}).done(function(data) {

				window.location = '/Request/list'

			});

		}else{
			alert("Canceled");
		}
	}


    function edit_company(value)
    {
        $.ajax({
            type: 'GET',
            url: "/Other/getcompanybyid/",
            data: { edit_comp: value }
        }).done(function(data) {
                var t = JSON.parse(data);
                $("#plc").val(t.company_name);
                $("#othertypes").val(t.company_id);
                //window.location = '/Request/list'

            });
    }
	
	
	
	
</script>
<div class="content-wrapper">
    
    <div class="">
        <h2 class="heading bold">List Company</h2>
    </div>
    
	
	<div class="content-main full">


        <div id="myModal" class="modal fade" role="dialog">
            <form class="default-form" action="/Other/submit" method="post">
                <input type="hidden" name="othertypes" id="othertypes" value="">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title" id="modal-header"></h4>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label class="control-label" id="lbl_id">Add New Company</label>
                                <div class="input-container-half">
                                    <input type="text" placeholder="" id="plc" name="txt_value">
                                </div>

                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-green" id="btn_oth">Add</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>

                    </div>

                </div>
            </form>
        </div>


					<div class="team-title">
						<div class="block">
                            <?php if($this->ob_LoginAuth->chk_menu_permission('Add_Company')){?>

                                <button class="md-font btn-green" data-toggle="modal" data-target="#myModal"><i class="fa fa-bell"></i> Add Company</button>
                            <?php } ?>
							<?php if($this->ob_LoginAuth->chk_menu_permission('Delete_Company')){ ?>
							    <button class="md-font btn-red" id="delbtn" onclick="del_con_checkit();"><i class="fa fa-trash"></i> Delete</button>
							<?php } ?>
							<?php if($this->ob_LoginAuth->chk_menu_permission('Import_Company')){ ?>
							    <button class="md-font btn-grey" onclick="window.location=''" disabled><i class="fa fa-arrow-circle-up"></i> Import</button>
							<?php } ?>
							<?php if($this->ob_LoginAuth->chk_menu_permission('Export_Company')){ ?>
							    <button class="md-font btn-grey" onclick="window.location='/Download/listexporttoexcel/export_id/19'" ><i class="fa fa-arrow-circle-down"></i> Export</button>
							<?php } ?>
						</div>
						<form class="search" id="search_form" action="" method="post" onsubmit="return check_sub();">
                            <input type="hidden" id="hide_del1" name="hide_del1" >
                            <input type="hidden" value="<?php print $this->num_row; ?>" id="num_row" name="num_row">
                            <input type="hidden" value="<?php print $this->page; ?>" id="page" name="page">
                            <input type="hidden" value="<?php print $order_col=$this->order_col; ?>" id="order_col" name="order_col">
                            <input type="hidden" value="<?php print $order_typ=$this->order_typ; ?>" id="order_typ" name="order_typ">
                            <input type="hidden" id="del_con_global" name="del_con_global" value=""/>
                            <input type="text" placeholder="Search" name="quick_search" onKeyPress="do_quick_search(event, this.value);" 
							value="<?php print $this->quick_search; ?>">
						</form>
					</div>

				
					<table class="table-full" data-tablesaw-mode="stack">
						<thead class="sortable">
							<tr>
								<th><input type="checkbox" id="selecctall"> #</th>
                                <th><?php print $this->ob_LoginAuth->set_excel_header('Company Name');?><?php print $this->page_sorting_images['company_name']; ?></th>
                                <th><?php print $this->ob_LoginAuth->set_excel_header('Added By');?><?php print $this->page_sorting_images['added_by']; ?></th>
                                <th><?php print $this->ob_LoginAuth->set_excel_header('Created Date');?><?php print $this->page_sorting_images['company_created_at']; ?></th>
								<?php
								if( $this->ob_LoginAuth->chk_menu_permission('Edit_Company')
									|| $this->ob_LoginAuth->chk_menu_permission('Delete_Company'))
								{
								?>
								<th>Manage</th>
								<?php
								}
								?>
				 
							
							</tr>
						</thead>
						<tbody>
							<?php
							$sl = 1;
							foreach($this->company_rows as $k=>$v)
							{
							$idd=$v['company_id'];
							?>
							<tr>
								<td><input type="checkbox" value='<?php echo $idd;?>' name="chk[]" id="del_con_<?php echo $sl;?>" class="checkbox1"> <?php // print $idd; ?></td>
                                <td><?php print $this->ob_LoginAuth->set_excel_values($v['company_name'],$idd); ?></td>
                                <td><?php print $this->ob_LoginAuth->set_excel_values($v['user_fname'].' '.$v['user_lname'],$idd); ?></td>
								<td><?php print $this->ob_LoginAuth->set_excel_values($v['company_created_at'],$idd); ?></td>
                                <?php
                                if( $this->ob_LoginAuth->chk_menu_permission('Edit_Company')
                                || $this->ob_LoginAuth->chk_menu_permission('Delete_Company'))
                                {
                                ?>
								<td>
								<?php if($this->ob_LoginAuth->chk_menu_permission('Edit_Company')) {?>
                                    <a href="javascript:void(0)" onclick="edit_company(<?php echo $idd;?>);" data-toggle="modal" data-target="#myModal" style="<?php echo $edit;?>">Edit</a> &nbsp;&nbsp;
                                <?php } ?>
								<?php if($this->ob_LoginAuth->chk_menu_permission('Delete_Company')) {?>
                                    <a href="/Other/company/del_id/<?php echo $v['company_id'];?>" style="<?php echo $del;?>"  onclick="return confirm('Are you sure you want to delete?')">Delete</a>
                                <?php } ?>
								
								</td>
                                <?php
                                }
                                ?>
							</tr>
							<?php
							$sl++;
							}
							?>
			<input type="hidden" id="del_con_tcount" value="<?php echo $sl; ?>"/>				
						</tbody>
					</table>
					<?php print $this->page_peginetion; ?>
					
					<!--<div class="content-main transparent right half">
						<button class="btn-grey">Cancel</button>
						<button class="btn-green">Add User</button>
					</div>-->
    </div>
				</div>
	
	
	
	
	
	
</div>