</div>
</body>
<!-- Main Body End -->
<script src="<?php print $this->site_asset; ?>js/jquery-2.1.4.min.js"></script>
<script src="<?php print $this->site_asset; ?>js/bootstrap-switch.min.js"></script>
<script src="<?php print $this->site_asset; ?>js/bootstrap.min.js"></script>
<script src="<?php print $this->site_asset; ?>js/tablesaw.js"></script>
<script src="<?php print $this->site_asset; ?>js/tablesaw-init.js"></script>
<script src="<?php print $this->site_asset; ?>js/script.js"></script>
<script src="<?php print $this->site_asset; ?>js/defined_functions.js"></script>
<script src="<?php print $this->site_asset; ?>js/defined_list_fucntions.js"></script>
<link href="<?php print $this->site_asset; ?>css/event-date.css" rel="stylesheet">

</html>