<?php
header("Cache-Control: private, max-age=0");
header("Expires: -1");
?>
<!DOCTYPE html>
<html>
<!-- Heading Start -->
<head>
    <title>Tranzgo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="<?php print $this->site_asset; ?>css/font-awesome.min.css" rel="stylesheet">
    <link href="<?php print $this->site_asset; ?>css/bootstrap-switch.css" rel="stylesheet">
    <link href="<?php print $this->site_asset; ?>css/style.css" rel="stylesheet">
    <link href="<?php print $this->site_asset; ?>css/easy-autocomplete.min.css" rel="stylesheet">

</head>
<!-- Heading End -->

<!-- Main Body Start -->
<body class="error-body no-top">
<div class="container">